### ISSUE TITLE
Uses File::Slurp, known to be buggy and vulnerable

### ISSUE THREAD

**Issue by karenetheridge** [fibo/Sweet-Home-pm#1]
e.g. look at https://rt.cpan.org/Ticket/Display.html?id=83126 and be dismayed

File::Slurp::Tiny and Path::Tiny are both excellent alternatives. See also http://shadow.cat/blog/matt-s-trout/mstpan-5/

**Comment by fibo** [comment]
Thank you very much! I just solved today an charset issue on a project for a customer. Then I noticed casually you opened this bug ahahah, coincidences. I released e new version of Sweet::Home, using File::Slurp::Tiny. I also added a test about utf8.
